[workspace]
members = [
    "common/fw",
    "common/bin",
    "common/ipk",
    "common/verify",
    "packages/elf-verify",
    "packages/ipk-verify",
    "packages/fw-extract",
    "packages/gen-manifest",
]
