[package]
name = "fw-extract"
version = "0.1.1"
edition = "2021"
authors = ["Mariotaku Lee <mariotaku.lee@gmail.com>"]
license = "Apache-2.0"
description = "Firmware symbols data and extractor utility"

[dependencies]
regex = { workspace = true }
path-slash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
semver = { workspace = true }
fw-lib = { path = "../../common/fw" }
bin-lib = { path = "../../common/bin" }

[dependencies.clap]
workspace = true
features = ["derive"]

[features]
linux-install = ["fw-lib/linux-install"]

[package.metadata.deb]
name = "webosbrew-toolbox-fw-symbols"
section = "devel"
assets = [
    ["target/release/fw-extract", "usr/bin/webosbrew-fw-symbols-extract", "755"],
    ["../../common/data/**/*", "usr/share/webosbrew/compat-checker/data/", "644"]
]
features = ["linux-install"]