[package]
name = "bin-lib"
version = "0.1.1"
edition = "2021"

[dependencies]
elf = "0.7.4"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
semver = { workspace = true }

[features]
linux-install = []