[package]
name = "bin-lib"
version = "0.1.1"
edition = "2021"

[dependencies]
elf = "0.7.2"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
semver = "1.0.18"

[features]
linux-install = []