[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
elf = "0.7.2"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
semver = "1.0.17"

[features]
linux-install = []